### ISSUE TITLE
Create release tag

### ISSUE THREAD

**Issue by estesp** [containerd/typeurl#17]
For ease with using with `go mod` we should tag typeurl. The package is very stable and has no significant changes for quite some time. I propose a simple v1.0.0.

cc: @crosbymichael @dims

**Comment by mikebrow** [comment]
SGTM... could also use the validate/vendor test in CI?

**Comment by dmcgowan** [comment]
> I propose a simple v1.0.0

Any reason to do 1.x.x instead of 0.x.x. For our libraries and non-release repositories, it seems better to avoid the headaches associated with the "guarantees" around the Go interfaces when doing 1.0 and avoid confusion related to the containerd release numbers. Just a feeling though, I don't feel super strong about it but am curious if anyone else has any opinions.

**Comment by mikebrow** [comment]
IMO if you have shipped a product as a GA that includes public interfaces.. you now own those public interfaces and should treat them as such with a GA version tag. If you need a new v2 one that's fine to.

**Comment by estesp** [comment]
@dmcgowan at this point, I'm fine with 0.x.x given the purpose is related to simpler use of `go mod`, which can be achieved with either.

**Comment by mikebrow** [comment]
https://github.com/containerd/typeurl/releases/tag/v1.0.0
